# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setMaximumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainicon/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{\n"
"border-image: url(:/login_bg/images/bg.png);\n"
"}\n"
"QLabel{\n"
"font-weight:bold;\n"
"}")
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(130, 40, 351, 111))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setObjectName("title_label")
        self.login_Button = QtWidgets.QPushButton(Form)
        self.login_Button.setGeometry(QtCore.QRect(332, 300, 91, 41))
        self.login_Button.setStyleSheet(" QPushButton\n"
"                    {\n"
"font: 9pt \"仿宋\";\n"
"                     text-align : center;\n"
"                     background-color : white;\n"
"    background-color: rgb(217, 235, 255);\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 20px;}\n"
"                     QPushButton:pressed\n"
"                     {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.login_Button.setObjectName("login_Button")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 177, 241, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acc_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.acc_label.setFont(font)
        self.acc_label.setObjectName("acc_label")
        self.horizontalLayout.addWidget(self.acc_label)
        self.Account_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.Account_lineEdit.setObjectName("Account_lineEdit")
        self.horizontalLayout.addWidget(self.Account_lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 237, 241, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pass_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.horizontalLayout_2.addWidget(self.pass_label)
        self.Password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.horizontalLayout_2.addWidget(self.Password_lineEdit)
        self.register_Button = QtWidgets.QPushButton(Form)
        self.register_Button.setGeometry(QtCore.QRect(180, 300, 91, 41))
        self.register_Button.setStyleSheet(" QPushButton\n"
"                    {\n"
"font: 9pt \"仿宋\";\n"
"                     text-align : center;\n"
"                     background-color : white;\n"
"    background-color: rgb(217, 235, 255);\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 20px;}\n"
"                     QPushButton:pressed\n"
"                     {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.register_Button.setObjectName("register_Button")

        self.retranslateUi(Form)
        self.login_Button.clicked.connect(Form.check_login)
        self.register_Button.clicked.connect(Form.register)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录界面"))
        self.title_label.setText(_translate("Form", "数字图像篡改定位系统"))
        self.login_Button.setText(_translate("Form", "登录"))
        self.acc_label.setText(_translate("Form", "账  号："))
        self.pass_label.setText(_translate("Form", "密  码："))
        self.register_Button.setText(_translate("Form", "注册"))
import images_rc
import mainwin_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
