# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1250, 726)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1250, 726))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainicon/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setStyleSheet("\n"
"QListWidget\n"
"{\n"
"    \n"
"    font:15pt \"仿宋\" ;\n"
"    font-weight:bold;\n"
"    color:rgb(200,200,200);\n"
"    border:0px solid gray;\n"
"    padding:0px 0px 0px 0px;;\n"
"    \n"
"    background-image: url(:/main_bg/images/bg.png);\n"
"\n"
"}\n"
"/**列表项*/\n"
"QListWidget::item\n"
"{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    height:120px;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border:0px solid gray;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"   \n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item::selected:active\n"
"{ \n"
"    color:white;\n"
"    border:0px solid white;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    color:white;\n"
"    border-width:0;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(3000, 1800))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"\n"
"    border-image: url(:/main_bg/images/bg.png);\n"
"}\n"
"QPushButton{\n"
"    font: 15pt \"仿宋\";\n"
"     text-align : center;\n"
"    background-color: rgb(204, 242, 255);\n"
"    font-weight: bold;\n"
"    border-color: gray;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    padding: 0px;\n"
"    height : 14px;\n"
"    border-style: outset;\n"
"   }\n"
"QPushButton:pressed{\n"
"    font: 15pt \"仿宋\";\n"
"    text-align : center;\n"
"    background-color : light gray;\n"
"    font: bold;\n"
"    border-color: gray;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    height : 14px;\n"
"    border-style: outset;\n"
"}\n"
"QLineEdit{\n"
"    border-radius:10px;\n"
"}\n"
"QLabel{\n"
"    font-weight:bold;\n"
"}\n"
"")
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.detect_page = QtWidgets.QWidget()
        self.detect_page.setObjectName("detect_page")
        self.label_6 = QtWidgets.QLabel(self.detect_page)
        self.label_6.setGeometry(QtCore.QRect(190, 30, 181, 41))
        self.label_6.setStyleSheet("font: 20pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.detect_page)
        self.label_7.setGeometry(QtCore.QRect(660, 30, 141, 41))
        self.label_7.setStyleSheet("font: 20pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_7.setObjectName("label_7")
        self.load_tamper_btn = QtWidgets.QPushButton(self.detect_page)
        self.load_tamper_btn.setGeometry(QtCore.QRect(180, 495, 171, 51))
        self.load_tamper_btn.setObjectName("load_tamper_btn")
        self.tamper_pic = QtWidgets.QLabel(self.detect_page)
        self.tamper_pic.setGeometry(QtCore.QRect(100, 90, 350, 350))
        self.tamper_pic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tamper_pic.setText("")
        self.tamper_pic.setObjectName("tamper_pic")
        self.result_pic = QtWidgets.QLabel(self.detect_page)
        self.result_pic.setGeometry(QtCore.QRect(560, 90, 350, 350))
        self.result_pic.setMaximumSize(QtCore.QSize(1060, 640))
        self.result_pic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.result_pic.setText("")
        self.result_pic.setObjectName("result_pic")
        self.start_detect_btn = QtWidgets.QPushButton(self.detect_page)
        self.start_detect_btn.setGeometry(QtCore.QRect(420, 590, 171, 51))
        self.start_detect_btn.setObjectName("start_detect_btn")
        self.tamper_pic_addr = QtWidgets.QLineEdit(self.detect_page)
        self.tamper_pic_addr.setGeometry(QtCore.QRect(380, 500, 461, 41))
        self.tamper_pic_addr.setStyleSheet("font: 14pt \"仿宋\";")
        self.tamper_pic_addr.setObjectName("tamper_pic_addr")
        self.start_detect_btn_2 = QtWidgets.QPushButton(self.detect_page)
        self.start_detect_btn_2.setGeometry(QtCore.QRect(870, 630, 121, 51))
        self.start_detect_btn_2.setObjectName("start_detect_btn_2")
        self.stackedWidget.addWidget(self.detect_page)
        self.email_page = QtWidgets.QWidget()
        self.email_page.setObjectName("email_page")
        self.btn_tamper_zip = QtWidgets.QPushButton(self.email_page)
        self.btn_tamper_zip.setGeometry(QtCore.QRect(204, 270, 261, 41))
        self.btn_tamper_zip.setObjectName("btn_tamper_zip")
        self.label_25 = QtWidgets.QLabel(self.email_page)
        self.label_25.setGeometry(QtCore.QRect(138, 192, 331, 50))
        self.label_25.setStyleSheet("font: 20pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_25.setObjectName("label_25")
        self.email_lineEdit = QtWidgets.QLineEdit(self.email_page)
        self.email_lineEdit.setGeometry(QtCore.QRect(488, 200, 391, 40))
        self.email_lineEdit.setStyleSheet("font: 14pt \"仿宋\";")
        self.email_lineEdit.setText("")
        self.email_lineEdit.setReadOnly(False)
        self.email_lineEdit.setPlaceholderText("")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.btn_email = QtWidgets.QPushButton(self.email_page)
        self.btn_email.setGeometry(QtCore.QRect(440, 610, 141, 51))
        self.btn_email.setObjectName("btn_email")
        self.label_26 = QtWidgets.QLabel(self.email_page)
        self.label_26.setGeometry(QtCore.QRect(290, 60, 441, 71))
        self.label_26.setStyleSheet("font: 30pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_26.setObjectName("label_26")
        self.gif_label = QtWidgets.QLabel(self.email_page)
        self.gif_label.setGeometry(QtCore.QRect(384, 360, 214, 15))
        self.gif_label.setText("")
        self.gif_label.setObjectName("gif_label")
        self.tamper_addr = QtWidgets.QLineEdit(self.email_page)
        self.tamper_addr.setGeometry(QtCore.QRect(490, 270, 391, 41))
        self.tamper_addr.setStyleSheet("font: 14pt \"仿宋\";")
        self.tamper_addr.setText("")
        self.tamper_addr.setReadOnly(False)
        self.tamper_addr.setPlaceholderText("")
        self.tamper_addr.setObjectName("tamper_addr")
        self.label = QtWidgets.QLabel(self.email_page)
        self.label.setGeometry(QtCore.QRect(130, 400, 121, 41))
        self.label.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.running_label = QtWidgets.QLabel(self.email_page)
        self.running_label.setGeometry(QtCore.QRect(260, 400, 531, 40))
        self.running_label.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.running_label.setObjectName("running_label")
        self.label_3 = QtWidgets.QLabel(self.email_page)
        self.label_3.setGeometry(QtCore.QRect(130, 470, 121, 41))
        self.label_3.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.email_page)
        self.label_4.setGeometry(QtCore.QRect(184, 540, 70, 41))
        self.label_4.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_4.setObjectName("label_4")
        self.num_comp_label = QtWidgets.QLabel(self.email_page)
        self.num_comp_label.setGeometry(QtCore.QRect(260, 470, 61, 40))
        self.num_comp_label.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.num_comp_label.setText("")
        self.num_comp_label.setObjectName("num_comp_label")
        self.total_label = QtWidgets.QLabel(self.email_page)
        self.total_label.setGeometry(QtCore.QRect(260, 540, 61, 40))
        self.total_label.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.total_label.setText("")
        self.total_label.setObjectName("total_label")
        self.label_9 = QtWidgets.QLabel(self.email_page)
        self.label_9.setGeometry(QtCore.QRect(320, 470, 61, 40))
        self.label_9.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.email_page)
        self.label_10.setGeometry(QtCore.QRect(320, 540, 61, 40))
        self.label_10.setStyleSheet("font: 15pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.email_page)
        self.log_page = QtWidgets.QWidget()
        self.log_page.setObjectName("log_page")
        self.label_27 = QtWidgets.QLabel(self.log_page)
        self.label_27.setGeometry(QtCore.QRect(340, 20, 371, 31))
        self.label_27.setStyleSheet("font: 20pt \"仿宋\";\n"
"font-weight:bold;")
        self.label_27.setObjectName("label_27")
        self.pushButton = QtWidgets.QPushButton(self.log_page)
        self.pushButton.setGeometry(QtCore.QRect(270, 640, 191, 51))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.log_page)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 961, 561))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_3 = QtWidgets.QPushButton(self.log_page)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 640, 191, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.log_page)
        self.info_page = QtWidgets.QWidget()
        self.info_page.setObjectName("info_page")
        self.modify_title = QtWidgets.QLabel(self.info_page)
        self.modify_title.setGeometry(QtCore.QRect(338, 50, 121, 61))
        self.modify_title.setStyleSheet("font: 30pt \"仿宋\";\n"
"font-weight:bold;")
        self.modify_title.setObjectName("modify_title")
        self.newpasscon_label = QtWidgets.QLabel(self.info_page)
        self.newpasscon_label.setGeometry(QtCore.QRect(210, 480, 150, 33))
        self.newpasscon_label.setStyleSheet("font: 20pt \"仿宋\";")
        self.newpasscon_label.setObjectName("newpasscon_label")
        self.newpass_con_lineedit = QtWidgets.QLineEdit(self.info_page)
        self.newpass_con_lineedit.setGeometry(QtCore.QRect(480, 480, 324, 39))
        self.newpass_con_lineedit.setStyleSheet("font: 20pt \"仿宋\";")
        self.newpass_con_lineedit.setObjectName("newpass_con_lineedit")
        self.confirm_change_btn = QtWidgets.QPushButton(self.info_page)
        self.confirm_change_btn.setGeometry(QtCore.QRect(408, 570, 171, 61))
        self.confirm_change_btn.setStyleSheet("")
        self.confirm_change_btn.setObjectName("confirm_change_btn")
        self.newpass_lineedit = QtWidgets.QLineEdit(self.info_page)
        self.newpass_lineedit.setGeometry(QtCore.QRect(480, 406, 324, 39))
        self.newpass_lineedit.setStyleSheet("font: 20pt \"仿宋\";")
        self.newpass_lineedit.setObjectName("newpass_lineedit")
        self.Id_label = QtWidgets.QLabel(self.info_page)
        self.Id_label.setGeometry(QtCore.QRect(480, 196, 321, 33))
        self.Id_label.setStyleSheet("font: 20pt \"仿宋\";")
        self.Id_label.setObjectName("Id_label")
        self.acc_label = QtWidgets.QLabel(self.info_page)
        self.acc_label.setGeometry(QtCore.QRect(284, 196, 102, 33))
        self.acc_label.setStyleSheet("font: 20pt \"仿宋\";")
        self.acc_label.setObjectName("acc_label")
        self.new_password_label = QtWidgets.QLabel(self.info_page)
        self.new_password_label.setGeometry(QtCore.QRect(244, 406, 136, 33))
        self.new_password_label.setStyleSheet("font: 20pt \"仿宋\";")
        self.new_password_label.setObjectName("new_password_label")
        self.Id_label_3 = QtWidgets.QLabel(self.info_page)
        self.Id_label_3.setGeometry(QtCore.QRect(479, 263, 321, 33))
        self.Id_label_3.setStyleSheet("font: 20pt \"仿宋\";")
        self.Id_label_3.setObjectName("Id_label_3")
        self.acc_label_3 = QtWidgets.QLabel(self.info_page)
        self.acc_label_3.setGeometry(QtCore.QRect(283, 263, 102, 33))
        self.acc_label_3.setStyleSheet("font: 20pt \"仿宋\";")
        self.acc_label_3.setObjectName("acc_label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.info_page)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 630, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.nametiltelabel = QtWidgets.QLabel(self.info_page)
        self.nametiltelabel.setGeometry(QtCore.QRect(470, 50, 121, 61))
        self.nametiltelabel.setStyleSheet("font: 30pt \"仿宋\";\n"
"font-weight:bold;")
        self.nametiltelabel.setText("")
        self.nametiltelabel.setObjectName("nametiltelabel")
        self.acc_label_4 = QtWidgets.QLabel(self.info_page)
        self.acc_label_4.setGeometry(QtCore.QRect(214, 330, 151, 33))
        self.acc_label_4.setStyleSheet("font: 20pt \"仿宋\";")
        self.acc_label_4.setObjectName("acc_label_4")
        self.institutelabel = QtWidgets.QLabel(self.info_page)
        self.institutelabel.setGeometry(QtCore.QRect(480, 330, 321, 33))
        self.institutelabel.setStyleSheet("font: 20pt \"仿宋\";")
        self.institutelabel.setObjectName("institutelabel")
        self.stackedWidget.addWidget(self.info_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        self.load_tamper_btn.clicked.connect(Form.upload_tamper)
        self.pushButton.clicked.connect(Form.check_logs)
        self.confirm_change_btn.clicked.connect(Form.change_password)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.btn_email.clicked.connect(Form.strat_multi_detect)
        self.start_detect_btn.clicked.connect(Form.start_detect)
        self.btn_tamper_zip.clicked.connect(Form.upload_tamper_zip)
        self.pushButton_2.clicked.connect(Form.back)
        self.pushButton_3.clicked.connect(Form.download_db)
        self.start_detect_btn_2.clicked.connect(Form.download_one)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数字图像篡改定位系统"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "单张图像定位"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "批量图像定位"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "操作日志查询"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "个人账户管理"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("Form", "待检测图像"))
        self.label_7.setText(_translate("Form", "定位结果"))
        self.load_tamper_btn.setText(_translate("Form", "上传篡改图像"))
        self.start_detect_btn.setText(_translate("Form", "开始检测"))
        self.start_detect_btn_2.setText(_translate("Form", "保存"))
        self.btn_tamper_zip.setText(_translate("Form", "上传篡改图像压缩包"))
        self.label_25.setText(_translate("Form", "请输入接收结果邮箱:"))
        self.btn_email.setText(_translate("Form", "确认"))
        self.label_26.setText(_translate("Form", "多张图像批量定位"))
        self.label.setText(_translate("Form", "正在检测："))
        self.running_label.setText(_translate("Form", "无"))
        self.label_3.setText(_translate("Form", "已经检测："))
        self.label_4.setText(_translate("Form", "一共："))
        self.label_9.setText(_translate("Form", "张"))
        self.label_10.setText(_translate("Form", "张"))
        self.label_27.setText(_translate("Form", "近期10条系统使用记录"))
        self.pushButton.setText(_translate("Form", "查看历史记录"))
        self.pushButton_3.setText(_translate("Form", "下载"))
        self.modify_title.setText(_translate("Form", "您好，"))
        self.newpasscon_label.setText(_translate("Form", "确认密码："))
        self.confirm_change_btn.setText(_translate("Form", "确认修改"))
        self.Id_label.setText(_translate("Form", "11111111"))
        self.acc_label.setText(_translate("Form", "账号："))
        self.new_password_label.setText(_translate("Form", "新密码："))
        self.Id_label_3.setText(_translate("Form", "1695100184@qq.com"))
        self.acc_label_3.setText(_translate("Form", "邮箱："))
        self.pushButton_2.setText(_translate("Form", "退出登录"))
        self.acc_label_4.setText(_translate("Form", "工作机构："))
        self.institutelabel.setText(_translate("Form", "南京信息工程大学"))
import mainwin_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
