# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 499)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(397, 499))
        Form.setMaximumSize(QtCore.QSize(397, 499))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mainicon/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{background-image: url(:/main_bg/images/bg.png);}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 161, 51))
        self.label.setStyleSheet("font: 18pt \"宋体\";\n"
"font-weight:bold;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 68, 72, 41))
        self.label_2.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 125, 72, 41))
        self.label_3.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 304, 72, 41))
        self.label_4.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 364, 111, 41))
        self.label_5.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 74, 171, 30))
        self.lineEdit.setStyleSheet("border-radius: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 131, 171, 30))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 310, 171, 30))
        self.lineEdit_3.setStyleSheet("border-radius: 10px;")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 370, 171, 30))
        self.lineEdit_4.setStyleSheet("border-radius: 10px;")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.register_Button = QtWidgets.QPushButton(Form)
        self.register_Button.setGeometry(QtCore.QRect(80, 440, 91, 41))
        self.register_Button.setStyleSheet(" QPushButton\n"
"                    {\n"
"font: 9pt \"仿宋\";\n"
"                     text-align : center;\n"
"                     background-color : white;\n"
"    background-color: rgb(217, 235, 255);\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 20px;}\n"
"                     QPushButton:pressed\n"
"                     {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.register_Button.setObjectName("register_Button")
        self.register_Button_2 = QtWidgets.QPushButton(Form)
        self.register_Button_2.setGeometry(QtCore.QRect(240, 440, 91, 41))
        self.register_Button_2.setStyleSheet(" QPushButton\n"
"                    {\n"
"font: 9pt \"仿宋\";\n"
"                     text-align : center;\n"
"                     background-color : white;\n"
"    background-color: rgb(217, 235, 255);\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 20px;}\n"
"                     QPushButton:pressed\n"
"                     {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.register_Button_2.setObjectName("register_Button_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 184, 72, 41))
        self.label_6.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 190, 171, 30))
        self.lineEdit_5.setStyleSheet("border-radius: 10px;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 244, 111, 41))
        self.label_7.setStyleSheet("font: 14pt \"宋体\";\n"
"font-weight:bold;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 250, 171, 30))
        self.lineEdit_6.setStyleSheet("border-radius: 10px;")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(Form)
        self.register_Button.clicked.connect(Form.commit_info)
        self.register_Button_2.clicked.connect(Form.back)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "注册"))
        self.label.setText(_translate("Form", "新用户注册"))
        self.label_2.setText(_translate("Form", "账号："))
        self.label_3.setText(_translate("Form", "邮箱："))
        self.label_4.setText(_translate("Form", "密码："))
        self.label_5.setText(_translate("Form", "确认密码："))
        self.register_Button.setText(_translate("Form", "提交"))
        self.register_Button_2.setText(_translate("Form", "返回"))
        self.label_6.setText(_translate("Form", "姓名："))
        self.label_7.setText(_translate("Form", "工作机构："))
import mainwin_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
